import { Inter } from "next/font/google";
import "./globals.css";
import { inter, poppins } from "./ui/fonts";
import Sidenav from "./ui/sidenav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Sidenav />
        {children}
      </body>
    </html>
  );
}
